cloudevents:
  source:
    client:
      targetUri: ${sink:http://localhost:8080}
      requestTimeout: 4000
      connectTimeout: 10000
      readTimeout: 2000
      maxPerRoute: 100
      maxTotal: 100
    event:
      eventType: Source.File.Usage
      source: /parser-demo
      contentType: application/json

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: notifications
    gcp:
      project-id: ${gcp.project.id}
      credentials:
        encoded-key: ${gcp.credentials.encoded-key}